"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-05-09 11:47:53.315867

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Spec gereği (database-schema.md): pgcrypto + marketlens schema.
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")
    op.execute("CREATE SCHEMA IF NOT EXISTS marketlens")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('economic_events',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('event_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('impact', sa.String(length=20), nullable=True),
    sa.Column('forecast', sa.String(length=50), nullable=True),
    sa.Column('previous', sa.String(length=50), nullable=True),
    sa.Column('actual', sa.String(length=50), nullable=True),
    sa.Column('source', sa.String(length=50), server_default='forexfactory', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_economic_events')),
    sa.UniqueConstraint('event_time', 'name', 'currency', name='uq_economic_event_time_name_ccy'),
    schema='marketlens'
    )
    op.create_index('idx_events_high_impact', 'economic_events', ['event_time'], unique=False, schema='marketlens', postgresql_where=sa.text("impact = 'high'"))
    op.create_index('idx_events_upcoming', 'economic_events', ['event_time'], unique=False, schema='marketlens')
    op.create_table('macro_metrics',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('metric_code', sa.String(length=30), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('value', sa.Numeric(precision=30, scale=8), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_macro_metrics')),
    sa.UniqueConstraint('metric_code', 'timestamp', name='uq_macro_metric_code_ts'),
    schema='marketlens'
    )
    op.create_index('idx_macro_metrics_lookup', 'macro_metrics', ['metric_code', sa.literal_column('timestamp DESC')], unique=False, schema='marketlens')
    op.create_table('symbols',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('display_name', sa.String(length=50), nullable=False),
    sa.Column('asset_type', sa.String(length=20), nullable=False),
    sa.Column('sector', sa.String(length=20), nullable=True),
    sa.Column('quote_currency', sa.String(length=10), nullable=False),
    sa.Column('exchange', sa.String(length=20), nullable=False),
    sa.Column('has_futures', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_symbols')),
    sa.UniqueConstraint('code', name=op.f('uq_symbols_code')),
    schema='marketlens'
    )
    op.create_index('idx_symbols_active', 'symbols', ['is_active', 'sort_order'], unique=False, schema='marketlens')
    op.create_index('idx_symbols_sector', 'symbols', ['sector'], unique=False, schema='marketlens')
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('telegram_chat_id', sa.String(length=50), nullable=True),
    sa.Column('telegram_username', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    schema='marketlens'
    )
    op.create_table('analyses',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('symbol_id', sa.Integer(), nullable=True),
    sa.Column('triggered_by', sa.String(length=20), nullable=False),
    sa.Column('current_price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('overall_bias', sa.String(length=20), nullable=True),
    sa.Column('alignment_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('alignment_label', sa.String(length=20), nullable=True),
    sa.Column('setup_quality', sa.CHAR(length=1), nullable=True),
    sa.Column('setup_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('confidence_level', sa.String(length=20), nullable=True),
    sa.Column('confidence_trade_count', sa.Integer(), nullable=True),
    sa.Column('actual_win_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('counter_trend_warnings_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('counter_trend_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('trade_quality_score', sa.Integer(), nullable=True),
    sa.Column('trade_quality_verdict', sa.String(length=20), nullable=True),
    sa.Column('trade_quality_factors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('macro_regime', sa.String(length=30), nullable=True),
    sa.Column('macro_modifier', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('no_trade_active', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('no_trade_reason', sa.String(length=255), nullable=True),
    sa.Column('market_session', sa.String(length=20), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['symbol_id'], ['marketlens.symbols.id'], name=op.f('fk_analyses_symbol_id_symbols')),
    sa.ForeignKeyConstraint(['user_id'], ['marketlens.users.id'], name=op.f('fk_analyses_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analyses')),
    schema='marketlens'
    )
    op.create_index('idx_analyses_quality', 'analyses', ['setup_quality'], unique=False, schema='marketlens', postgresql_where=sa.text("setup_quality IN ('A', 'B')"))
    op.create_index('idx_analyses_regime', 'analyses', ['macro_regime', sa.literal_column('created_at DESC')], unique=False, schema='marketlens')
    op.create_index('idx_analyses_user_symbol', 'analyses', ['user_id', 'symbol_id', sa.literal_column('created_at DESC')], unique=False, schema='marketlens')
    op.create_table('correlations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('symbol_a_id', sa.Integer(), nullable=False),
    sa.Column('symbol_b_code', sa.String(length=20), nullable=False),
    sa.Column('period_days', sa.Integer(), server_default='30', nullable=False),
    sa.Column('timeframe', sa.String(length=10), server_default='4H', nullable=False),
    sa.Column('correlation', sa.Numeric(precision=5, scale=3), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['symbol_a_id'], ['marketlens.symbols.id'], name=op.f('fk_correlations_symbol_a_id_symbols')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_correlations')),
    schema='marketlens'
    )
    op.create_index('idx_correlations_lookup', 'correlations', ['symbol_a_id', 'symbol_b_code', sa.literal_column('computed_at DESC')], unique=False, schema='marketlens')
    op.create_table('daily_risk_tracker',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('trades_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('risk_used_pct', sa.Numeric(precision=5, scale=2), server_default='0', nullable=False),
    sa.Column('consecutive_losses', sa.Integer(), server_default='0', nullable=False),
    sa.Column('current_risk_pct', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('risk_reduction_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_paused', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('pause_reason', sa.String(length=100), nullable=True),
    sa.Column('paused_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['marketlens.users.id'], name=op.f('fk_daily_risk_tracker_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_daily_risk_tracker')),
    sa.UniqueConstraint('user_id', 'date', name='uq_daily_risk_user_date'),
    schema='marketlens'
    )
    op.create_table('price_cache',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('symbol_id', sa.Integer(), nullable=False),
    sa.Column('timeframe', sa.String(length=10), nullable=False),
    sa.Column('open_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open_price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('high_price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('low_price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('close_price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('volume', sa.Numeric(precision=30, scale=8), nullable=False),
    sa.Column('quote_volume', sa.Numeric(precision=30, scale=8), nullable=True),
    sa.Column('trade_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['symbol_id'], ['marketlens.symbols.id'], name=op.f('fk_price_cache_symbol_id_symbols')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_price_cache')),
    sa.UniqueConstraint('symbol_id', 'timeframe', 'open_time', name='uq_price_cache_symbol_tf_time'),
    schema='marketlens'
    )
    op.create_index('idx_price_cache_lookup', 'price_cache', ['symbol_id', 'timeframe', sa.literal_column('open_time DESC')], unique=False, schema='marketlens')
    op.create_table('user_settings',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('account_balance', sa.Numeric(precision=20, scale=2), server_default='3000', nullable=False),
    sa.Column('risk_per_trade_pct', sa.Numeric(precision=4, scale=2), server_default='2.0', nullable=False),
    sa.Column('max_leverage', sa.Integer(), server_default='10', nullable=False),
    sa.Column('daily_max_trades', sa.Integer(), server_default='5', nullable=False),
    sa.Column('daily_max_risk_pct', sa.Numeric(precision=5, scale=2), server_default='4.0', nullable=False),
    sa.Column('auto_pause_after_losses', sa.Integer(), server_default='3', nullable=False),
    sa.Column('smart_reduction_enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('risk_after_2_losses_pct', sa.Numeric(precision=4, scale=2), server_default='1.5', nullable=False),
    sa.Column('risk_after_3_losses_pct', sa.Numeric(precision=4, scale=2), server_default='1.0', nullable=False),
    sa.Column('volatility_adjustment_enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('scanner_enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('scanner_interval_min', sa.Integer(), server_default='15', nullable=False),
    sa.Column('scanner_min_quality', sa.String(length=1), server_default='B', nullable=False),
    sa.Column('volatility_alert_5m_pct', sa.Numeric(precision=4, scale=2), server_default='2.0', nullable=False),
    sa.Column('volatility_alert_1h_pct', sa.Numeric(precision=4, scale=2), server_default='4.0', nullable=False),
    sa.Column('volatility_alert_4h_pct', sa.Numeric(precision=4, scale=2), server_default='7.0', nullable=False),
    sa.Column('telegram_alerts_enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('alert_setup_found', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('alert_volatility', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('alert_critical_news', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('alert_stop_warn_pct', sa.Numeric(precision=4, scale=2), server_default='1.0', nullable=False),
    sa.Column('alert_target_warn_pct', sa.Numeric(precision=4, scale=2), server_default='1.0', nullable=False),
    sa.Column('alert_funding_threshold', sa.Numeric(precision=6, scale=4), server_default='0.0500', nullable=False),
    sa.Column('alert_whale_threshold_usd', sa.Numeric(precision=20, scale=2), server_default='5000000', nullable=False),
    sa.Column('no_trade_macro_events', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('no_trade_weekly_close', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('no_trade_high_volatility', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('no_trade_asian_session', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('auto_ma_selection', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('default_timeframes', sa.ARRAY(sa.String(length=10)), server_default='{4H,1D}', nullable=False),
    sa.Column('default_modules', sa.ARRAY(sa.String(length=20)), server_default='{trend,momentum,futures}', nullable=False),
    sa.Column('theme', sa.String(length=20), server_default='dark', nullable=False),
    sa.Column('sidebar_collapsed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('anthropic_api_key', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['marketlens.users.id'], name=op.f('fk_user_settings_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_user_settings')),
    schema='marketlens'
    )
    op.create_table('watchlists',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('is_default', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_favorite', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['marketlens.users.id'], name=op.f('fk_watchlists_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_watchlists')),
    schema='marketlens'
    )
    op.create_table('confluence_scores',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('analysis_id', sa.UUID(), nullable=False),
    sa.Column('timeframe', sa.String(length=10), nullable=False),
    sa.Column('local_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('trend_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('momentum_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('volume_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('volatility_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('futures_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('macro_modifier', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('final_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('indicators', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['marketlens.analyses.id'], name=op.f('fk_confluence_scores_analysis_id_analyses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_confluence_scores')),
    schema='marketlens'
    )
    op.create_index('idx_confluence_analysis', 'confluence_scores', ['analysis_id'], unique=False, schema='marketlens')
    op.create_table('scenarios',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('analysis_id', sa.UUID(), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('probability', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('entry_low', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('entry_high', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('target_1', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('target_1_pct', sa.Numeric(precision=5, scale=2), server_default='40', nullable=False),
    sa.Column('target_1_rationale', sa.String(length=255), nullable=True),
    sa.Column('target_2', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('target_2_pct', sa.Numeric(precision=5, scale=2), server_default='35', nullable=False),
    sa.Column('target_2_rationale', sa.String(length=255), nullable=True),
    sa.Column('target_3', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('target_3_pct', sa.Numeric(precision=5, scale=2), server_default='25', nullable=False),
    sa.Column('target_3_rationale', sa.String(length=255), nullable=True),
    sa.Column('stop_loss', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('invalidation_note', sa.String(length=255), nullable=True),
    sa.Column('risk_reward', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('atr_distance', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('support_levels', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('resistance_levels', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('summary_text', sa.Text(), nullable=True),
    sa.Column('warnings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['marketlens.analyses.id'], name=op.f('fk_scenarios_analysis_id_analyses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scenarios')),
    schema='marketlens'
    )
    op.create_index('idx_scenarios_analysis', 'scenarios', ['analysis_id'], unique=False, schema='marketlens')
    op.create_table('setups',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('symbol_id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.UUID(), nullable=True),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('timeframe', sa.String(length=10), nullable=False),
    sa.Column('quality', sa.CHAR(length=1), nullable=False),
    sa.Column('confluence', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('macro_regime', sa.String(length=30), nullable=True),
    sa.Column('risk_reward', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('setup_type', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notified', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['marketlens.analyses.id'], name=op.f('fk_setups_analysis_id_analyses')),
    sa.ForeignKeyConstraint(['symbol_id'], ['marketlens.symbols.id'], name=op.f('fk_setups_symbol_id_symbols')),
    sa.ForeignKeyConstraint(['user_id'], ['marketlens.users.id'], name=op.f('fk_setups_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_setups')),
    schema='marketlens'
    )
    op.create_index('idx_setups_active', 'setups', ['user_id', 'status', sa.literal_column('created_at DESC')], unique=False, schema='marketlens')
    op.create_index('idx_setups_quality', 'setups', ['quality'], unique=False, schema='marketlens', postgresql_where=sa.text("status = 'active'"))
    op.create_index('idx_setups_type', 'setups', ['setup_type'], unique=False, schema='marketlens')
    op.create_table('watchlist_symbols',
    sa.Column('watchlist_id', sa.UUID(), nullable=False),
    sa.Column('symbol_id', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['symbol_id'], ['marketlens.symbols.id'], name=op.f('fk_watchlist_symbols_symbol_id_symbols')),
    sa.ForeignKeyConstraint(['watchlist_id'], ['marketlens.watchlists.id'], name=op.f('fk_watchlist_symbols_watchlist_id_watchlists'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('watchlist_id', 'symbol_id', name=op.f('pk_watchlist_symbols')),
    schema='marketlens'
    )
    op.create_table('trades',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('symbol_id', sa.Integer(), nullable=False),
    sa.Column('setup_id', sa.UUID(), nullable=True),
    sa.Column('analysis_id', sa.UUID(), nullable=True),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('entry_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('position_size_usd', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('leverage', sa.Integer(), nullable=False),
    sa.Column('margin_used', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('planned_stop', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('planned_target1', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('planned_target2', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('planned_target3', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('exit_price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('exit_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('exit_reason', sa.String(length=50), nullable=True),
    sa.Column('pnl_usd', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('pnl_pct', sa.Numeric(precision=7, scale=3), nullable=True),
    sa.Column('r_multiple', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('funding_paid', sa.Numeric(precision=20, scale=2), server_default='0', nullable=False),
    sa.Column('fees_paid', sa.Numeric(precision=20, scale=2), server_default='0', nullable=False),
    sa.Column('setup_quality_at_entry', sa.CHAR(length=1), nullable=True),
    sa.Column('macro_regime_at_entry', sa.String(length=30), nullable=True),
    sa.Column('timeframe', sa.String(length=10), nullable=True),
    sa.Column('market_session', sa.String(length=20), nullable=True),
    sa.Column('setup_type', sa.String(length=50), nullable=True),
    sa.Column('user_note', sa.Text(), nullable=True),
    sa.Column('tags', sa.ARRAY(sa.String(length=50)), nullable=True),
    sa.Column('trailing_stop_active', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('breakeven_set', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('partial_closes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='open', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['marketlens.analyses.id'], name=op.f('fk_trades_analysis_id_analyses')),
    sa.ForeignKeyConstraint(['setup_id'], ['marketlens.setups.id'], name=op.f('fk_trades_setup_id_setups')),
    sa.ForeignKeyConstraint(['symbol_id'], ['marketlens.symbols.id'], name=op.f('fk_trades_symbol_id_symbols')),
    sa.ForeignKeyConstraint(['user_id'], ['marketlens.users.id'], name=op.f('fk_trades_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trades')),
    schema='marketlens'
    )
    op.create_index('idx_trades_closed', 'trades', ['user_id', sa.literal_column('exit_time DESC')], unique=False, schema='marketlens', postgresql_where=sa.text("status = 'closed'"))
    op.create_index('idx_trades_session', 'trades', ['market_session'], unique=False, schema='marketlens', postgresql_where=sa.text("status = 'closed'"))
    op.create_index('idx_trades_setup_type', 'trades', ['setup_type'], unique=False, schema='marketlens', postgresql_where=sa.text("status = 'closed'"))
    op.create_index('idx_trades_user_status', 'trades', ['user_id', 'status', sa.literal_column('entry_time DESC')], unique=False, schema='marketlens')
    op.create_table('alerts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('symbol_id', sa.Integer(), nullable=True),
    sa.Column('alert_type', sa.String(length=40), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('trigger_condition', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('delivered', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('related_setup_id', sa.UUID(), nullable=True),
    sa.Column('related_trade_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['related_setup_id'], ['marketlens.setups.id'], name=op.f('fk_alerts_related_setup_id_setups')),
    sa.ForeignKeyConstraint(['related_trade_id'], ['marketlens.trades.id'], name=op.f('fk_alerts_related_trade_id_trades')),
    sa.ForeignKeyConstraint(['symbol_id'], ['marketlens.symbols.id'], name=op.f('fk_alerts_symbol_id_symbols')),
    sa.ForeignKeyConstraint(['user_id'], ['marketlens.users.id'], name=op.f('fk_alerts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alerts')),
    schema='marketlens'
    )
    op.create_index('idx_alerts_priority', 'alerts', ['priority', sa.literal_column('created_at DESC')], unique=False, schema='marketlens')
    op.create_index('idx_alerts_user_undelivered', 'alerts', ['user_id', 'delivered', sa.literal_column('created_at DESC')], unique=False, schema='marketlens')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_alerts_user_undelivered', table_name='alerts', schema='marketlens')
    op.drop_index('idx_alerts_priority', table_name='alerts', schema='marketlens')
    op.drop_table('alerts', schema='marketlens')
    op.drop_index('idx_trades_user_status', table_name='trades', schema='marketlens')
    op.drop_index('idx_trades_setup_type', table_name='trades', schema='marketlens', postgresql_where=sa.text("status = 'closed'"))
    op.drop_index('idx_trades_session', table_name='trades', schema='marketlens', postgresql_where=sa.text("status = 'closed'"))
    op.drop_index('idx_trades_closed', table_name='trades', schema='marketlens', postgresql_where=sa.text("status = 'closed'"))
    op.drop_table('trades', schema='marketlens')
    op.drop_table('watchlist_symbols', schema='marketlens')
    op.drop_index('idx_setups_type', table_name='setups', schema='marketlens')
    op.drop_index('idx_setups_quality', table_name='setups', schema='marketlens', postgresql_where=sa.text("status = 'active'"))
    op.drop_index('idx_setups_active', table_name='setups', schema='marketlens')
    op.drop_table('setups', schema='marketlens')
    op.drop_index('idx_scenarios_analysis', table_name='scenarios', schema='marketlens')
    op.drop_table('scenarios', schema='marketlens')
    op.drop_index('idx_confluence_analysis', table_name='confluence_scores', schema='marketlens')
    op.drop_table('confluence_scores', schema='marketlens')
    op.drop_table('watchlists', schema='marketlens')
    op.drop_table('user_settings', schema='marketlens')
    op.drop_index('idx_price_cache_lookup', table_name='price_cache', schema='marketlens')
    op.drop_table('price_cache', schema='marketlens')
    op.drop_table('daily_risk_tracker', schema='marketlens')
    op.drop_index('idx_correlations_lookup', table_name='correlations', schema='marketlens')
    op.drop_table('correlations', schema='marketlens')
    op.drop_index('idx_analyses_user_symbol', table_name='analyses', schema='marketlens')
    op.drop_index('idx_analyses_regime', table_name='analyses', schema='marketlens')
    op.drop_index('idx_analyses_quality', table_name='analyses', schema='marketlens', postgresql_where=sa.text("setup_quality IN ('A', 'B')"))
    op.drop_table('analyses', schema='marketlens')
    op.drop_table('users', schema='marketlens')
    op.drop_index('idx_symbols_sector', table_name='symbols', schema='marketlens')
    op.drop_index('idx_symbols_active', table_name='symbols', schema='marketlens')
    op.drop_table('symbols', schema='marketlens')
    op.drop_index('idx_macro_metrics_lookup', table_name='macro_metrics', schema='marketlens')
    op.drop_table('macro_metrics', schema='marketlens')
    op.drop_index('idx_events_upcoming', table_name='economic_events', schema='marketlens')
    op.drop_index('idx_events_high_impact', table_name='economic_events', schema='marketlens', postgresql_where=sa.text("impact = 'high'"))
    op.drop_table('economic_events', schema='marketlens')
    # ### end Alembic commands ###
